# Galaxy A34 5G config
MODEL_NAME="Galaxy A34 5G"
DEVICE_MODEL_NAME="Galaxy A34 5G"
DEVICE_ACTUAL_MODEL="SM-A346B"
CODENAME="a34x"
PLATFORM="mt6877"
DEVICE_VNDK_VERSION=33

# Stock firmware details for download
STOCK_MODEL="SM-A346B"
STOCK_CSC="EUX"

# Source firmware details for download (Same base as m51)
MODEL="SM-S711U1"
CSC="AIO"

# Extra firmware which is optional
EXTRA_MODEL="SM-S711U1"
EXTRA_CSC="AIO"

# Output
FILESYSTEM="erofs"
DEVICE_SUPER_PARTITION_SIZE=11744051200
DEVICE_SUPER_GROUP_BASIC_SIZE=11739856896

# Specs
DEVICE_HAVE_SPEN_SUPPORT=false
DEVICE_HAVE_QHD_PANEL=false
DEVICE_HAVE_HIGH_REFRESH_RATE=true
DEVICE_HAVE_AMOLED_DISPLAY=true
DEVICE_SUPPORT_HAPTIC_AUDIO_VIBRATOR=false
DEVICE_HAVE_ESIM_SUPPORT=false
DEVICE_HAVE_DUAL_SPEAKER=true
DEVICE_FINGERPRINT_SENSOR_TYPE="google_touch_display_optical,settings=3"

# Custom props
DEVICE_SIOP_POLICY_FILENAME="siop_a34x_mt6877v"
DEVICE_DISPLAY_HFR_MODE="2"
DEVICE_DISPLAY_REFRESH_RATE_VALUES_HZ="60,120"
DEVICE_DEFAULT_REFRESH_RATE="120"
DEVICE_MDNIE_MODE="37905"
DEVICE_AUTO_BRIGHTNESS_LEVEL="5"